[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "21.0.1-preview.3" }
[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
